### ISSUE TITLE
Utils/Telegram.php new file not working

### ISSUE THREAD

**Issue by alohane** [pennyMorant/zeropanel#10]
Utils/Telegram.php new file not working

PHP Fatal error:  Uncaught RuntimeException: Stream is detached in /www/wwwroot/zeropanel/vendor/guzzlehttp/psr7/src/Stream.php:246
Stack trace:
#0 /www/wwwroot/zeropanel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(414): GuzzleHttp\Psr7\Stream->write()
#1 [internal function]: GuzzleHttp\Handler\CurlFactory::GuzzleHttp\Handler\{closure}()
#2 /www/wwwroot/zeropanel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(167): curl_multi_exec()
#3 /www/wwwroot/zeropanel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(185): GuzzleHttp\Handler\CurlMultiHandler->tick()
#4 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute()
#5 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Utils.php(134): GuzzleHttp\Promise\Promise->wait()
#10 /www/wwwroot/zeropanel/vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php(48): GuzzleHttp\Promise\Utils::unwrap()
#11 [internal function]: Telegram\Bot\HttpClients\GuzzleHttpClient->__destruct()
#12 {main}
  thrown in /www/wwwroot/zeropanel/vendor/guzzlehttp/psr7/src/Stream.php on line 246

Fatal error: Uncaught RuntimeException: Stream is detached in /www/wwwroot/zeropanel/vendor/guzzlehttp/psr7/src/Stream.php:246
Stack trace:
#0 /www/wwwroot/zeropanel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(414): GuzzleHttp\Psr7\Stream->write()
#1 [internal function]: GuzzleHttp\Handler\CurlFactory::GuzzleHttp\Handler\{closure}()
#2 /www/wwwroot/zeropanel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(167): curl_multi_exec()
#3 /www/wwwroot/zeropanel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(185): GuzzleHttp\Handler\CurlMultiHandler->tick()
#4 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute()
#5 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /www/wwwroot/zeropanel/vendor/guzzlehttp/promises/src/Utils.php(134): GuzzleHttp\Promise\Promise->wait()
#10 /www/wwwroot/zeropanel/vendor/irazasyed/telegram-bot-sdk/src/HttpClients/GuzzleHttpClient.php(48): GuzzleHttp\Promise\Utils::unwrap()
#11 [internal function]: Telegram\Bot\HttpClients\GuzzleHttpClient->__destruct()
#12 {main}
  thrown in /www/wwwroot/zeropanel/vendor/guzzlehttp/psr7/src/Stream.php on line 246

**Comment by pennyMorant** [comment]
How to reproduce this problem

**Comment by alohane** [comment]
can you give me your telegram account, i want discuss more. Because i also fix many bug in your code.

**Comment by alohane** [comment]
> How to reproduce this problem

Keep old pushToAdmin function

**Comment by pennyMorant** [comment]
> can you give me your telegram account, i want discuss more. Because i also fix many bug in your code.

Please PR

**Comment by alohane** [comment]
> > can you give me your telegram account, i want discuss more. Because i also fix many bug in your code.
> 
> Please PR

@jresshin, i message to you in group
